# Adds namespace to all resources.
namespace: knode-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: knode-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
# - ../rbac
- ../knode

patchesStrategicMerge:
- patch-configmap.yaml
- patch-daemonset.yaml
